#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --ntasks-per-node=40
#SBATCH --threads-per-core=1
#SBATCH -A cli@cpu
#SBATCH --hint=nomultithread
#SBATCH -J JOB_
#SBATCH -e zjob.e%j
#SBATCH -o zjob.o%j
#SBATCH --time=0:30:00


module unload DCM
module load DCM/4.0.2
cd /linkhome/rech/genlgg01/rcli002/CONFIGS/CONFIG_eORCA1/eORCA1-GJM2020
#make cleaninst
make install
make

